# W13B1C: guarded repair for malformed PowerShell generated by Rust.
# Targets only the two Get-CimInstance Win32_LogicalDisk filter expressions.
# Does not write to the Vault registry, migrate state, or launch Desktop.
# Requires the exact published W13B1 GREEN source blob for the targeted file.
[CmdletBinding()]
param([string]$Repository = 'G:\Cortex')
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path -LiteralPath $Repository).Path
$relative = 'crates/cortex_registry/src/lib.rs'
$path = Join-Path $repo 'crates\cortex_registry\src\lib.rs'
if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Target missing: $path" }

$expectedCommit = 'e868824747bf1a811ed500190be2792b7fbdfaa8'
$expectedBlob = '89f9200a644cab2f01ad5d05a86102969af71263'
$head = (& git -C $repo rev-parse --verify HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or $head -ne $expectedCommit) {
    throw "Unexpected Cortex HEAD $head; expected $expectedCommit. Do not apply over another checkpoint."
}
$modified = @(& git -C $repo status --porcelain -- $relative)
if ($LASTEXITCODE -ne 0 -or $modified.Count -ne 0) {
    throw "Target Rust file has local changes; refusing to overwrite: $($modified -join '; ')"
}
$blob = (& git -C $repo hash-object -- $relative).Trim()
if ($LASTEXITCODE -ne 0 -or $blob -ne $expectedBlob) {
    throw "Unexpected target source blob $blob; expected $expectedBlob. No changes made."
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
$old = [System.IO.File]::ReadAllText($path, $utf8)
$pattern = '(\$logical=)Get-CimInstance Win32_LogicalDisk -Filter [^\r\n]*? -ErrorAction SilentlyContinue'
$re = [System.Text.RegularExpressions.Regex]::new($pattern)
$matches = $re.Matches($old)
if ($matches.Count -ne 2) {
    throw "Expected exactly two malformed identity-filter expressions; found $($matches.Count). No changes made."
}
$correct = 'Get-CimInstance Win32_LogicalDisk -ErrorAction SilentlyContinue | Where-Object {{ $_.DeviceID -eq $device }}'
$updated = $re.Replace($old, [System.Text.RegularExpressions.MatchEvaluator]{
    param($match)
    $match.Groups[1].Value + $correct
})
if ($updated -eq $old -or ([regex]::Matches($updated, [regex]::Escape($correct))).Count -ne 2) {
    throw 'Replacement did not produce exactly two corrected Rust format! expressions. No changes made.'
}

$recovery = Join-Path $repo 'artifacts/recovery/W13B1C'
[System.IO.Directory]::CreateDirectory($recovery) | Out-Null
$backup = Join-Path $recovery ('lib.rs.before-W13B1C-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.bak')
$temp = Join-Path (Split-Path -Parent $path) ('.cortex-w13b1c-' + [guid]::NewGuid().ToString('N') + '.tmp')
try {
    [System.IO.File]::WriteAllText($temp, $updated, $utf8)
    [System.IO.File]::Replace($temp, $path, $backup, $true)
} finally {
    if ([System.IO.File]::Exists($temp)) { [System.IO.File]::Delete($temp) }
}
Write-Host '[PASS] Replaced both malformed Windows logical-disk queries.'
Write-Host "[INFO] Source backup: $backup"
Write-Host '[INFO] Registry, Vault, project data, and Desktop state were not modified.'
Write-Host '[NEXT] Run cargo fmt --all -- --check; git diff --check; then FULL in PCC.'
