[package]
name = "forge-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
forge-core = { path = "../forge-core" }
forge-process = { path = "../forge-process" }
forge-state = { path = "../forge-state" }

[lints]
workspace = true
