#!/usr/bin/env python3
"""Compare two authenticated Cortex source rollups, never modify either source tree.

A difference report is evidence, not an automatic merge, preferred version, or patch.
Both inputs must be SOURCE_ROLLUP_MANIFEST.json archives generated by CortexSourceRollup.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path

import CortexSourceRollup as rollup

REPORT_SCHEMA = "cortex.source_comparison.v1"
MAX_SIDECAR_BYTES = 512
PREVIEW_MAX = 100
HEX = re.compile(r"[0-9a-fA-F]{64}")


class CompareError(RuntimeError):
    pass


def sidecar_status(archive: Path, archive_sha: str) -> str:
    """Absence is disclosed; any present invalid sidecar is a hard failure."""
    sidecar = Path(str(archive) + ".sha256")
    if not sidecar.exists() and not sidecar.is_symlink():
        return "missing"
    if rollup.link_or_reparse(sidecar) or not sidecar.is_file():
        raise CompareError("linked or non-file checksum sidecar: " + archive.name)
    if sidecar.stat().st_size > MAX_SIDECAR_BYTES:
        raise CompareError("oversized checksum sidecar: " + archive.name)
    try:
        raw = sidecar.read_text(encoding="ascii")
    except (UnicodeError, OSError) as exc:
        raise CompareError("unreadable checksum sidecar: " + archive.name) from exc
    match = re.fullmatch(r"([0-9a-fA-F]{64})  ([^\r\n]+)\r?\n?", raw)
    if not match or match.group(2) != archive.name or match.group(1).lower() != archive_sha:
        raise CompareError("checksum sidecar mismatch: " + archive.name)
    return "verified"


def read_rollup(archive: Path) -> dict:
    archive = archive.absolute()
    if not archive.is_file() or rollup.link_or_reparse(archive):
        raise CompareError("not an ordinary source rollup archive: " + str(archive))
    # Complete content verification runs BEFORE reading/using the inventory.
    evidence = rollup.verify(archive)
    if evidence["schema"] != rollup.SCHEMA:
        raise CompareError("not a Cortex source rollup: " + str(archive))
    sidecar = sidecar_status(archive, str(evidence["sha256"]))
    with zipfile.ZipFile(archive) as zf:
        manifest = json.loads(zf.read(rollup.MANIFEST))
    records = manifest["files"]
    if not isinstance(records, list):
        raise CompareError("invalid source inventory in " + archive.name)
    inventory = {}
    for item in records:
        if not isinstance(item, dict) or not isinstance(item.get("path"), str):
            raise CompareError("invalid source inventory entry in " + archive.name)
        path = item["path"]
        rollup.safe_name(path)
        if not isinstance(item.get("bytes"), int) or item["bytes"] < 0 or not isinstance(item.get("sha256"), str) or not HEX.fullmatch(item["sha256"]):
            raise CompareError("invalid source digest entry: " + path)
        folded = path.casefold()
        if folded in inventory:
            raise CompareError("case-insensitive source collision: " + path)
        inventory[folded] = {"path": path, "bytes": item["bytes"], "sha256": item["sha256"].lower()}
    lineage = manifest.get("patchLineage")
    if not isinstance(lineage, dict):
        raise CompareError("source rollup missing patch lineage: " + archive.name)
    receipt_ids = []
    for receipt in lineage.get("appliedReceipts", []):
        if not isinstance(receipt, dict) or not isinstance(receipt.get("patchId"), str):
            raise CompareError("invalid applied-patch metadata: " + archive.name)
        if receipt.get("status", "").casefold() == "applied":
            receipt_ids.append(receipt["patchId"])
    pending_ids = []
    for patch in lineage.get("pendingTransports", []):
        if not isinstance(patch, dict) or not isinstance(patch.get("patchId"), str):
            raise CompareError("invalid pending-patch metadata: " + archive.name)
        pending_ids.append(patch["patchId"])
    git = manifest.get("git")
    if not isinstance(git, dict):
        raise CompareError("source rollup missing Git metadata: " + archive.name)
    return {
        "name": archive.name,
        "sha256": evidence["sha256"],
        "sidecar": sidecar,
        "files": inventory,
        "sourceFileCount": evidence["fileCount"],
        "sourceBytes": evidence["sourceBytes"],
        "excludedCount": evidence["excludedCount"],
        "git": {"repository": git.get("repository"), "head": git.get("head"),
                "branch": git.get("branch"), "changedPathCount": git.get("changedPathCount")},
        "appliedPatches": sorted(set(receipt_ids), key=str.casefold),
        "pendingPatches": sorted(set(pending_ids), key=str.casefold),
    }


def compare(left_archive: Path, right_archive: Path) -> dict:
    left = read_rollup(left_archive)
    right = read_rollup(right_archive)
    lfiles, rfiles = left.pop("files"), right.pop("files")
    shared = lfiles.keys() & rfiles.keys()
    changed = []
    for folded in sorted(shared):
        old, new = lfiles[folded], rfiles[folded]
        if old["sha256"] != new["sha256"] or old["bytes"] != new["bytes"] or old["path"] != new["path"]:
            changed.append({"path": old["path"], "rightPath": new["path"],
                            "leftSha256": old["sha256"], "rightSha256": new["sha256"],
                            "leftBytes": old["bytes"], "rightBytes": new["bytes"]})
    only_left = [lfiles[key] for key in sorted(lfiles.keys() - rfiles.keys())]
    only_right = [rfiles[key] for key in sorted(rfiles.keys() - lfiles.keys())]
    lp, rp = set(left["appliedPatches"]), set(right["appliedPatches"])
    left_pending, right_pending = set(left["pendingPatches"]), set(right["pendingPatches"])
    return {
        "schema": REPORT_SCHEMA,
        "meaning": "Read-only comparison; neither side is automatically authoritative or safe to overwrite.",
        "left": left,
        "right": right,
        "differences": {
            "onlyLeft": only_left,
            "onlyRight": only_right,
            "changed": changed,
            "onlyLeftAppliedPatchIds": sorted(lp - rp, key=str.casefold),
            "onlyRightAppliedPatchIds": sorted(rp - lp, key=str.casefold),
            "onlyLeftPendingPatchIds": sorted(left_pending - right_pending, key=str.casefold),
            "onlyRightPendingPatchIds": sorted(right_pending - left_pending, key=str.casefold),
        },
        "counts": {"onlyLeft": len(only_left), "onlyRight": len(only_right), "changed": len(changed),
                   "sameContent": len(shared) - len(changed), "leftTotal": len(lfiles), "rightTotal": len(rfiles)},
    }


def bounded_report(report: dict, limit: int) -> dict:
    """Never misrepresent preview as a complete file listing."""
    if limit < 0 or limit > PREVIEW_MAX:
        raise CompareError("--preview must be between 0 and 100")
    result = dict(report)
    result["differences"] = {}
    for key, items in report["differences"].items():
        if key in ("onlyLeft", "onlyRight", "changed"):
            result["differences"][key] = items[:limit]
        else:
            result["differences"][key] = items
    result["preview"] = {"perCategoryLimit": limit, "complete": all(
        len(report["differences"][key]) <= limit for key in ("onlyLeft", "onlyRight", "changed")),
        "useFullFlagForCompleteInventory": True}
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare two verified Cortex SOURCE rollups; no source changes")
    parser.add_argument("--left", type=Path, required=True, help="older or first SOURCE rollup ZIP")
    parser.add_argument("--right", type=Path, required=True, help="newer or second SOURCE rollup ZIP")
    parser.add_argument("--preview", type=int, default=30, help="maximum listed source files per diff group (0..100)")
    parser.add_argument("--full", action="store_true", help="print every differing source file (may be large)")
    args = parser.parse_args(argv)
    try:
        report = compare(args.left, args.right)
        result = report if args.full else bounded_report(report, args.preview)
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0  # Differences are expected; failure indicates invalid evidence, not difference.
    except (CompareError, rollup.RollupError, OSError, ValueError, KeyError, TypeError,
            zipfile.BadZipFile, zipfile.LargeZipFile) as exc:
        print("SOURCE_COMPARISON_FAILED=" + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
