#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

STORAGE_PATHS_VERSION = "PCC-STORAGE-PATHS-0.4"


def _safe_json(path: Path) -> dict[str, Any] | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return None
    return data if isinstance(data, dict) else None


def storage_policy(project_root: Path | None = None) -> dict[str, Any]:
    if project_root:
        path = project_root.expanduser().resolve() / "config" / "cortex" / "storage_policy.v1.json"
        data = _safe_json(path)
        if data:
            return data
    return {}


def _windows_drive_available(path: Path) -> bool:
    drive = path.drive
    if not drive:
        return True
    try:
        return Path(drive + "\\").exists()
    except OSError:
        return False


def _runtime_root() -> Path:
    configured = str(os.environ.get("CORTEX_RUNTIME_ROOT") or "").strip()
    if configured:
        return Path(configured).expanduser().resolve()
    # PCCStoragePaths.py lives at <cortex-root>/tools/control.  The Cortex runtime
    # root is machine/application authority and must not change when the active
    # project switches to Havenwild or another registered workspace.
    return Path(__file__).resolve().parents[2]


def runtime_volume_root() -> Path:
    """Return the volume that physically contains the Cortex runtime.

    On Windows this deliberately returns the drive root (for example ``E:\\``)
    rather than persisting the transient drive letter anywhere else.  The same
    external disk may therefore appear as E:, G:, or another letter on a
    different machine without changing its logical Vault authority.
    """
    runtime = _runtime_root()
    if os.name == "nt" and runtime.drive:
        return Path(runtime.drive + "\\")
    anchor = runtime.anchor
    return Path(anchor) if anchor else runtime


def _portable_drive_root_policy_enabled() -> bool:
    if os.name != "nt":
        return False
    candidates = [
        _runtime_root() / "config" / "cortex" / "portable_drive_root_vault.v1.json",
    ]
    for path in candidates:
        data = _safe_json(path)
        if not data:
            continue
        if str(data.get("schema") or "") != "cortex.portable_drive_root_vault.v1":
            continue
        return bool(data.get("enabled")) and str(data.get("mode") or "") == "repository_drive_root"
    return False


def portable_relative_to_runtime_volume(path: Path) -> str | None:
    """Return a stable volume-relative path for files beside Cortex."""
    resolved = path.expanduser().resolve()
    volume = runtime_volume_root().resolve()
    try:
        relative = resolved.relative_to(volume)
    except ValueError:
        return None
    return relative.as_posix().strip("/")


def resolve_portable_volume_path(relative: str) -> Path:
    cleaned = str(relative or "").replace("\\", "/").strip("/")
    return (runtime_volume_root() / Path(cleaned)).resolve() if cleaned else runtime_volume_root().resolve()


def _bootstrap_vault_root() -> Path | None:
    """Read the persisted machine Vault authority written by Cortex bootstrap.

    The GUI can be launched by several Windows surfaces, and not every ancestry
    keeps CORTEX_VAULT_ROOT in its process environment.  bootstrap-env.cmd is the
    durable machine/session handoff generated by Bootstrap-CortexEnvironment.ps1,
    so native project PCCs must be able to recover the same authority from it.
    """
    path = _runtime_root() / ".cortex" / "bootstrap-env.cmd"
    if not path.is_file():
        return None
    try:
        lines = path.read_text(encoding="utf-8-sig", errors="replace").splitlines()
    except OSError:
        return None
    for key in ("CORTEX_VAULT_ROOT", "PCC_VAULT_ROOT"):
        prefix = f'set "{key}='
        for raw in lines:
            line = raw.strip()
            if not line.casefold().startswith(prefix.casefold()):
                continue
            value = line[len(prefix):]
            if value.endswith('"'):
                value = value[:-1]
            value = value.strip()
            if value:
                return Path(value).expanduser().resolve()
    return None


def resolve_vault_root(project_root: Path | None = None) -> Path:
    """Resolve the single Vault authority used by PCC and managed projects.

    A process-level override remains the highest authority.  Otherwise, when the
    repository enables ``repository_drive_root`` portability, the physical volume
    containing Cortex wins over any persisted bootstrap drive letter.  This is
    what allows one external disk to mount as E:, G:, etc. without creating a
    second Vault or pointing at a missing old drive.
    """
    override = os.environ.get("CORTEX_VAULT_ROOT") or os.environ.get("PCC_VAULT_ROOT")
    if override:
        return Path(override).expanduser().resolve()

    if _portable_drive_root_policy_enabled():
        return runtime_volume_root().resolve()

    bootstrapped = _bootstrap_vault_root()
    if bootstrapped is not None:
        return bootstrapped

    policy = storage_policy(project_root)
    if os.name == "nt":
        configured = str(policy.get("default_library_root_windows") or "D:\\CortexLibrary")
        candidate = Path(configured).expanduser()
        if _windows_drive_available(candidate):
            return candidate.resolve()
        base = Path(os.environ.get("LOCALAPPDATA") or (Path.home() / "AppData" / "Local"))
        return (base / "Cortex" / "Vault").resolve()

    base = Path(os.environ.get("XDG_DATA_HOME") or (Path.home() / ".local" / "share"))
    return (base / "cortex" / "vault").resolve()



_DEPENDENCY_LOCKFILES = (
    "Cargo.lock",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "uv.lock",
    "poetry.lock",
    "Pipfile.lock",
    "requirements.txt",
    "gradle.lockfile",
    "packages.lock.json",
    "vcpkg.json",
    "vcpkg-lock.json",
)


def dependency_compatibility(root: Path) -> dict[str, Any]:
    """Describe the project's dependency identity without creating private caches.

    Package-manager caches remain globally shared because those ecosystems already key cached
    artifacts by package/version/platform/ABI.  Project-local build/install trees stay isolated.
    The fingerprint is diagnostic/provenance metadata, not a reason to duplicate the cache.
    """
    root = root.expanduser().resolve()
    h = hashlib.sha256()
    locks: list[str] = []
    for rel in _DEPENDENCY_LOCKFILES:
        path = root / rel
        if not path.is_file():
            continue
        try:
            data = path.read_bytes()
        except OSError:
            continue
        locks.append(rel)
        h.update(rel.encode("utf-8")); h.update(b"\0"); h.update(data); h.update(b"\0")
    if not locks:
        # Build manifests still provide a stable coarse identity when a project has no lock file.
        for rel in ("Cargo.toml", "package.json", "pyproject.toml", "build.gradle", "build.gradle.kts", "vcpkg.json"):
            path = root / rel
            if not path.is_file():
                continue
            try:
                data = path.read_bytes()
            except OSError:
                continue
            locks.append(rel)
            h.update(rel.encode("utf-8")); h.update(b"\0"); h.update(data); h.update(b"\0")
    return {
        "policy": "share-compatible-isolate-conflicts",
        "fingerprint": h.hexdigest()[:24] if locks else "unlocked",
        "inputs": locks,
    }

def legacy_project_key(root: Path) -> str:
    """Pre-portability project key retained only for one-time namespace migration."""
    value = os.path.normcase(str(root.expanduser().resolve()))
    return hashlib.sha256(value.encode("utf-8", errors="replace")).hexdigest()[:20]


def project_identity(root: Path) -> str:
    """Stable project identity that survives external-drive letter changes.

    Projects stored beneath the governed Vault root are identified by their
    relative path (for example ``Source/Havenwild_Bevy`` or ``Cortex``), not by
    the transient Windows drive letter. Projects outside the Vault retain an
    absolute-path identity so unrelated folders cannot collide.
    """
    resolved = root.expanduser().resolve()
    vault = resolve_vault_root(resolved)
    try:
        relative = resolved.relative_to(vault)
    except ValueError:
        return "absolute:" + os.path.normcase(str(resolved))
    text = relative.as_posix().strip("/") or "."
    return "vault-relative:" + text.casefold()


def project_key(root: Path) -> str:
    value = project_identity(root)
    return hashlib.sha256(value.encode("utf-8", errors="replace")).hexdigest()[:20]


def project_vault_dir(root: Path) -> Path:
    return resolve_vault_root(root) / "projects" / project_key(root)


def object_store_dir(root: Path | None = None) -> Path:
    return resolve_vault_root(root) / "objects" / "sha256"


def shared_root(root: Path | None = None) -> Path:
    return resolve_vault_root(root) / "shared"


def dependency_paths(root: Path) -> dict[str, Path]:
    root = root.expanduser().resolve()
    vault = resolve_vault_root(root)
    shared = vault / "shared"
    key = project_key(root)
    return {
        "vault_root": vault,
        "project_vault": vault / "projects" / key,
        "cargo_home": shared / "dependencies" / "rust" / "cargo-home",
        # Build outputs remain project-namespaced to prevent executable/package
        # collisions.  Cross-project compiled reuse is supplied by sccache when
        # installed, while downloaded crate/git content is truly shared.
        "cargo_target_dir": shared / "build" / "rust" / "targets" / key,
        "sccache_dir": shared / "dependencies" / "rust" / "sccache",
        "sccache_home": shared / "toolchains" / "sccache",
        "npm_cache": shared / "dependencies" / "node" / "npm-cache",
        "pip_cache": shared / "dependencies" / "python" / "pip-cache",
        "gradle_home": shared / "dependencies" / "java" / "gradle-home",
        "nuget_packages": shared / "dependencies" / "dotnet" / "nuget-packages",
        "vcpkg_downloads": shared / "dependencies" / "cpp" / "vcpkg-downloads",
        "vcpkg_binary_cache": shared / "dependencies" / "cpp" / "vcpkg-binary-cache",
    }
